import os

SYNC_FIRST_WEEK_NUMBER = int(os.getenv("SYNC_FIRST_WEEK_NUMBER", "1"))
SYNC_DISCORD_WEBHOOK_URL = os.getenv("SYNC_DISCORD_WEBHOOK_URL", "")
SYNC_DISCORD_CHANNEL_ID = os.getenv("SYNC_DISCORD_CHANNEL_ID", "")
SYNC_DISCORD_MENTION_ROLE_ID = os.getenv("SYNC_DISCORD_MENTION_ROLE_ID", "")

SYNC_ZOOM_ROOM = os.getenv("SYNC_ZOOM_ROOM", "")
