import os

SYNC_FIRST_WEEK_NUMBER = int(os.getenv("SYNC_FIRST_WEEK_NUMBER", "1"))
SYNC_DISCORD_WEBHOOK_URL = os.getenv("SYNC_DISCORD_WEBHOOK_URL", "")
SYNC_DISCORD_CHANNEL_ID = os.getenv("SYNC_DISCORD_CHANNEL_ID", "")
SYNC_DISCORD_MENTION_ROLE_ID = os.getenv("SYNC_DISCORD_MENTION_ROLE_ID", "")

SYNC_ZOOM_SWITCH = str(os.getenv("SYNC_ZOOM_SWITCH", "False")) == "True"
SYNC_ZOOM_ROOM = os.getenv("SYNC_ZOOM_ROOM", "")


COVID_DISCORD_WEBHOOK_URL = os.getenv("COVID_DISCORD_WEBHOOK_URL", "")
COVID_CONTROL_ENABLED = str(os.getenv("COVID_CONTROL_ENABLED", "False")) == "True"