name: Notify about sync meeting

on:
  schedule:
    # every Wednesday at 12:50 MSK
    - cron: '50 9 * * 3'

permissions:
  contents: read

jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test notification with odd first week number
      env:
        SYNC_FIRST_WEEK_NUMBER: 1
        SYNC_DISCORD_WEBHOOK_URL: ${{ secrets.SYNC_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_CHANNEL_ID: ${{ secrets.SYNC_DISCORD_CHANNEL_ID }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.SYNC_DISCORD_MENTION_ROLE_ID }}
      run: |
        python src/sync_notification.py

    - name: Test notification with even first week number
      env:
        SYNC_FIRST_WEEK_NUMBER: 2
        SYNC_DISCORD_WEBHOOK_URL: ${{ secrets.SYNC_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_CHANNEL_ID: ${{ secrets.SYNC_DISCORD_CHANNEL_ID }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.SYNC_DISCORD_MENTION_ROLE_ID }}
      run: |
        python src/sync_notification.py
