name: Test all stuff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run test with odd first week number, ZOOM off
      env:
        SYNC_FIRST_WEEK_NUMBER: 1
        SYNC_DISCORD_WEBHOOK_URL: ${{ secrets.TEST_SYNC_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_CHANNEL_ID: ${{ secrets.TEST_SYNC_DISCORD_CHANNEL_ID }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.TEST_SYNC_DISCORD_MENTION_ROLE_ID }}
        SYNC_ZOOM_SWITCH: "False"
        SYNC_ZOOM_ROOM: ${{ secrets.TEST_SYNC_ZOOM_ROOM }}
      run: |
        python src/sync_notification.py

    - name: Run test with even first week number, ZOOM off
      env:
        SYNC_FIRST_WEEK_NUMBER: 2
        SYNC_DISCORD_WEBHOOK_URL: ${{ secrets.TEST_SYNC_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_CHANNEL_ID: ${{ secrets.TEST_SYNC_DISCORD_CHANNEL_ID }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.TEST_SYNC_DISCORD_MENTION_ROLE_ID }}
        SYNC_ZOOM_SWITCH: "False"
        SYNC_ZOOM_ROOM: ${{ secrets.TEST_SYNC_ZOOM_ROOM }}
      run: |
        python src/sync_notification.py

    - name: Run test with odd first week number, ZOOM on
      env:
        SYNC_FIRST_WEEK_NUMBER: 1
        SYNC_DISCORD_WEBHOOK_URL: ${{ secrets.TEST_SYNC_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_CHANNEL_ID: ${{ secrets.TEST_SYNC_DISCORD_CHANNEL_ID }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.TEST_SYNC_DISCORD_MENTION_ROLE_ID }}
        SYNC_ZOOM_SWITCH: "True"
        SYNC_ZOOM_ROOM: ${{ secrets.TEST_SYNC_ZOOM_ROOM }}
      run: |
        python src/sync_notification.py

    - name: Run test with even first week number, ZOOM on
      env:
        SYNC_FIRST_WEEK_NUMBER: 2
        SYNC_DISCORD_WEBHOOK_URL: ${{ secrets.TEST_SYNC_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_CHANNEL_ID: ${{ secrets.TEST_SYNC_DISCORD_CHANNEL_ID }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.TEST_SYNC_DISCORD_MENTION_ROLE_ID }}
        SYNC_ZOOM_SWITCH: "True"
        SYNC_ZOOM_ROOM: ${{ secrets.TEST_SYNC_ZOOM_ROOM }}
      run: |
        python src/sync_notification.py

    - name: Test COVID control enabled
      env:
        COVID_CONTROL_ENABLED: "True"
        COVID_DISCORD_WEBHOOK_URL: ${{ secrets.TEST_COVID_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.TEST_SYNC_DISCORD_MENTION_ROLE_ID }}
      run: |
        python src/covid_control.py

    - name: Test COVID control disabled
      env:
        COVID_CONTROL_ENABLED: "False"
        COVID_DISCORD_WEBHOOK_URL: ${{ secrets.TEST_COVID_DISCORD_WEBHOOK_URL }}
        SYNC_DISCORD_MENTION_ROLE_ID: ${{ secrets.TEST_SYNC_DISCORD_MENTION_ROLE_ID }}
      run: |
        python src/covid_control.py
